services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/vybe"
    restart: always
    command: nodemon --legacy-watch app.js

volumes:
  mongo-data:
